# English and Chinese UI labels of FritzingToBlender

ui_labels= {
    ('Operator', 'Fritzing Gerber Folder'): 'Fritzing Gerber文件夹',
    ('Operator', 'Import Gerber Folder'): '导入Gerber文件夹',
    ('*', 'Starting Gerber import ...'): '开始导入Gerber文件...',
    ('*', 'Fritzing Gerber Import Error'): '导入Gerber文件出错',
    ('*', 'Extruding ...'): '正在挤压成型...',
    ('*', 'Creating materials ...'): '正在创建材料...',
    ('*', 'Drilling holes ...'): '正在钻孔...',
    ('*', 'Cleaning drilled holes ...'): '正在清理孔...',
    ('*', 'Merging layers ...'): '正在融合各层...',
    ('*', 'Importing '): '正在导入',
    ('Operator', 'Fritzing Board Settings'): 'Fritzing线路板设置',
    ('*', 'Board Color:'): '线路板颜色：',
    ('*', 'Copper Color:'): '覆铜颜色：',
    ('*', 'Silk Color:'): '丝印颜色：',
    ('*', 'Board Thickness:'): '线路板厚度：',
    ('*', 'Cylinder Filter:'): '圆柱体过滤：',
    ('*', 'Drill Algorithm:'): '钻孔算法：',
    ('*', 'Auto Boolean (Fast)'): '自动布尔（快速）',
    ('*', 'No Drill'): '不钻孔',
    ('*', 'Booltron Non-Destructive Difference'): 'Booltron非破坏性差分',
    ('*', 'Fritzing Tools'): 'Fritzing工具',
    ('*', 'Import Gerber Folder'): '导入Gerber文件夹',
    ('*', 'Debug mode'): '调试模式',
    ('*', 'Optimize performance'): '优化性能',
    ('*', 'Gerber Import'): 'Gerber导入',
    ('*', 'Gerber Folder Import'): 'Gerber文件夹导入',
    ('*', 'Please select Gerber folder first'): '请先选择Gerber文件夹',
    ('*', 'Drill Import (Z-axis)'): '钻孔导入(Z轴)',
    ('Operator', 'Import Drill File (Z-axis)'): '导入钻孔文件(Z轴)',
    ('*', 'Import Drill File (Z-axis)'): '导入钻孔文件(Z轴)',
    ('*', 'Import Options'): '导入选项',
    ('*', 'Enable Debug Mode'): '启用调试模式',
    ('*', 'Tool Status'): '工具状态',
    ('*', 'Supported Drill File Formats'): '支持的钻孔文件格式',
    ('*', 'Excellon drill files:'): 'Excellon钻孔文件:',
    ('*', 'Please select a Drill file first'): '请先选择钻孔文件',
    ('*', 'Merge Cylinder Tools'): '合并圆柱工具',
    ('Operator', 'View Diameter Summary'): '查看直径摘要',
    ('*', 'Cylinder Merge Tools'): '合并圆柱工具',
    ('*', 'Process Selected Only'): '仅处理选中的物体',
    ('*', 'Rename Single Objects'): '单个对象也要重命名',
    ('*', 'Show Details'): '显示详细信息',
    ('*', 'No Drill_Cylinder objects found'): '未找到代表钻孔的圆柱对象',
    ('Operator', 'Cleanup Tool Numbers'): '清理工具编号',
    ('*', '{count} files found:'): '找到了{count}个文件：',
    ('*', 'Parse failed: '): '解析失败：',
    ('*', ' primitives'): '个图元',
    ('*', 'outline'): '轮廓',
    ('*', 'bottom'): '底板覆铜层',
    ('*', 'top'): '上板覆铜层',
    ('*', 'topsilk'): '上板丝印层',
    ('*', 'bottomsilk'): '底板丝印层',
    ('*', 'drill'): '钻孔',
    ('*', 'Parse failed'): '解析失败',
    ('*', 'Parse time: '): '解析耗时：',
    ('Operator', 'Import Gerber Files'): '导入Gerber文件',
    ('Operator', 'Clear All Imported Objects'): '清除所有导入对象',
    ('*', 'Total {stats_total_holes} drill cylinders'): '总共有{stats_total_holes}个钻孔圆柱',
    ('*', 'Total {stats_total_groups} tool numbers'): '共有{stats_total_groups}个工具编号',
    ('*', 'No Drill_Cylinder found'): '未找到代表钻孔的圆柱体',
    ('*', 'Cleanup complete: Deleted {collections_to_remove} collections, {objects_to_remove} objects'): '清理完成：删除了{collections_to_remove}个集合，{objects_to_remove}个对象',
    ('*', ' Meshes reduced: {meshes_before} -> {meshes_after}'): ' 网格减少：{meshes_before} -> {meshes_after}',
    ('*', ' Materials reduced: {materials_before} -> {materials_after}'): ' 材质减少：{materials_before} -> {materials_after}',
    ('*', 'Import complete: {object_count)} drills'): '导入完成：{object_count}个钻孔',
    ('*', 'Unknown error'): '未知错误',
    ('*', 'Geometry creation failed: {create_result_error}'): '创建几何体失败：{create_result_error}',
    ('*', 'Cleanup failed: {error}'): '清理失败：{error}',
    ('*', 'Import complete: {total_prims} primitives, {total_verts} vertices, {total_faces} faces'): '导入完成：{total_prims}个图元，{total_verts}个顶点，{total_faces}个面',
    ('*', 'No more Gerber files to process'): '没有更多的Gerber文件可处理',
    ('*', 'Import process error: {error}'): '导入时出错：{error}',
    ('Operator', 'Import Drill File'): '导入钻孔文件',
    ('*', 'Please select a valid Drill file'): '请选择一个有效的钻孔文件',
    ('*', 'File size: '): '文件大小：',
    ('*', 'File name: '): '文件名：',
    ('*', 'File type: Drill file'): '文件类型：钻孔文件',
    ('*', 'Direction: Along Z-axis (vertical)'): '方向：沿Z轴（垂直）',
    ('*', 'Primitives: '): '图元数量：',
    ('*', 'holes'): '个孔',
    ('*', '  ... and {num_more} more tool types'): '  ...还有{num_more}个工具类型',
    ('*', 'Drill tool properties group not found'): '未找到钻孔工具属性组',
    ('*', 'Summary complete: {num_groups} tool types, {num_holes} drill holes'): '摘要：{num_groups}个工具类型，{num_holes}个钻孔',
    ('*', 'Renumbering complete: {num_groups} tool types, renamed {renamed_count} objects'): '重命名完成：{num_groups}个工具类型，重命名{renamed_count}个对象',
    ('*', 'Complete! Processed {num_tools} tool types, {num_holes} drill holes'): '完成！处理了{num_tools}个工具类型，{num_holes}个钻孔',
    ('*', 'Failed to parse drill file: '): '解析钻孔文件失败：',
    ('*', 'Merging drill cylinders ...'): '正在合并钻孔圆柱 ...',
}

langs = {
    'zh': ui_labels,
    'zh_CN': ui_labels,
}
